INDEX_DATA = [
    {"sr": 1, "level1": "1",  "level2": "",      "title": "INTRODUCTION",                        "page": "9",  "bold": True},
    {"sr": "", "level1": "",  "level2": "1.1",   "title": "Background",                          "page": "9",  "bold": False},
    {"sr": "", "level1": "",  "level2": "1.2",   "title": "Objectives",                          "page": "10", "bold": False},
    {"sr": "", "level1": "",  "level2": "1.3",   "title": "Purpose, Scope, and Applicability",   "page": "11", "bold": False},
    {"sr": "", "level1": "",  "level2": "1.3.1", "title": "Purpose",                             "page": "11", "bold": False},
    {"sr": "", "level1": "",  "level2": "1.3.2", "title": "Scope",                               "page": "11", "bold": False},
    {"sr": "", "level1": "",  "level2": "1.3.3", "title": "Applicability",                       "page": "12", "bold": False},
    {"sr": "", "level1": "",  "level2": "1.4",   "title": "Achievements",                        "page": "12", "bold": False},
    {"sr": "", "level1": "",  "level2": "1.5",   "title": "Organization of Report",              "page": "12", "bold": False},

    {"sr": 2, "level1": "2",  "level2": "",      "title": "SURVEY OF TECHNOLOGIES",              "page": "13", "bold": True},

    {"sr": 3, "level1": "3",  "level2": "",      "title": "REQUIREMENT AND ANALYSIS",            "page": "14", "bold": True},
    {"sr": "", "level1": "",  "level2": "3.1",   "title": "Problem Definition",                  "page": "14", "bold": False},
    {"sr": "", "level1": "",  "level2": "3.2",   "title": "Requirement Specification",           "page": "15", "bold": False},
    {"sr": "", "level1": "",  "level2": "3.3",   "title": "Planning and Scheduling",             "page": "16", "bold": False},
    {"sr": "", "level1": "",  "level2": "3.4",   "title": "Software and Hardware Requirements",  "page": "18", "bold": False},
    {"sr": "", "level1": "",  "level2": "3.5",   "title": "Preliminary Product Description",     "page": "19", "bold": False},
    {"sr": "", "level1": "",  "level2": "3.6",   "title": "Conceptual Models",                   "page": "21", "bold": False},

    {"sr": 4, "level1": "4",  "level2": "",      "title": "SYSTEM DESIGN",                       "page": "34", "bold": True},
    {"sr": "", "level1": "",  "level2": "4.1",   "title": "Basic Modules",                       "page": "34", "bold": False},
    {"sr": "", "level1": "",  "level2": "4.2",   "title": "Data Design",                         "page": "36", "bold": False},
    {"sr": "", "level1": "",  "level2": "4.2.1", "title": "Schema Design",                       "page": "36", "bold": False},
    {"sr": "", "level1": "",  "level2": "4.2.2", "title": "Data Integrity and Constraints",      "page": "39", "bold": False},
    {"sr": "", "level1": "",  "level2": "4.3",   "title": "User Interface Design",               "page": "40", "bold": False},
    {"sr": "", "level1": "",  "level2": "4.4",   "title": "Security Issues",                     "page": "46", "bold": False},
    {"sr": "", "level1": "",  "level2": "4.5",   "title": "Test Cases Design",                   "page": "47", "bold": False},

    {"sr": 5, "level1": "5",  "level2": "",      "title": "IMPLEMENTATION AND TESTING",          "page": "48", "bold": True},
    {"sr": "", "level1": "",  "level2": "5.1",   "title": "Implementation Approach",             "page": "48", "bold": False},
    {"sr": "", "level1": "",  "level2": "5.2",   "title": "Coding Details and Code Efficiency",  "page": "53", "bold": False},
    {"sr": "", "level1": "",  "level2": "5.2.1", "title": "Code Efficiency",                     "page": "66", "bold": False},
    {"sr": "", "level1": "",  "level2": "5.3",   "title": "Testing Approach",                    "page": "67", "bold": False},
    {"sr": "", "level1": "",  "level2": "5.3.1", "title": "Unit Testing",                        "page": "67", "bold": False},
    {"sr": "", "level1": "",  "level2": "5.3.2", "title": "Integration Testing",                 "page": "67", "bold": False},
    {"sr": "", "level1": "",  "level2": "5.3.3", "title": "System Testing",                      "page": "67", "bold": False},
    {"sr": "", "level1": "",  "level2": "5.4",   "title": "Modifications and Improvements",      "page": "68", "bold": False},

    {"sr": 6, "level1": "6",  "level2": "",      "title": "RESULTS AND DISCUSSION",              "page": "69", "bold": True},
    {"sr": "", "level1": "",  "level2": "6.1",   "title": "Test Reports",                        "page": "69", "bold": False},
    {"sr": "", "level1": "",  "level2": "6.2",   "title": "User Documentation",                  "page": "70", "bold": False},

    {"sr": 7, "level1": "7",  "level2": "",      "title": "CONCLUSION",                          "page": "78", "bold": True},
    {"sr": "", "level1": "",  "level2": "7.1",   "title": "Conclusion",                          "page": "78", "bold": False},
    {"sr": "", "level1": "",  "level2": "7.2",   "title": "Limitations of the System",           "page": "78", "bold": False},
    {"sr": "", "level1": "",  "level2": "7.3",   "title": "Future Scope of the Project",         "page": "78", "bold": False},
]